2fa: 'MI4DMNTGGQYDEN3EGFRDQNLFGQ3WIMTDGNTGIMRVHBQTSM3BGM3A===='
bark: 'https://api.day.app/4j3Wffbcy8MdAxiP9QuDa9/'
api_key: 'fk212238-EEbBHfkuTmu6MoheLk992jObMV3QvnIi'
base_url: 'https://oa.api2d.net/v1/'